# Workflow name
name: 'Chromatic Deployment'

# Event for the workflow
on:
  push:
    branches:
      - '**'

# List of jobs
jobs:
  chromatic-deployment:
    # Operating System
    runs-on: ubuntu-latest
    environment: development
    defaults:
      run:
        working-directory: 'packages/app'
    # Job steps
    steps:
      - uses: actions/checkout@v1
      - name: 'Install dependencies'
        run: yarn
        working-directory: 'packages/app'
      - name: 'Publish to Chromatic'
        uses: chromaui/action@v1
        with:
          workingDir: 'packages/app'
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
